version: "3.8"

# Define a network to run all microservices on.
networks:
  ryver-network:

# Define each service to run on the network.
services:
  registry:
    image: ryver-registry
    container_name: ryver-registry
    build: ryver-registry
    ports:
      - "8761:8761"
    networks:
      - "ryver-network"
    environment:
      - EUREKA_INSTANCE_PREFERIPADDRESS=true

  gateway:
    image: ryver-gateway
    container_name: ryver-gateway
    build: ryver-gateway
    depends_on:
      - registry
    ports:
      - "8080:8080"
    networks:
      - "ryver-network"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ryver-registry:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  auth:
    image: ryver-auth
    container_name: ryver-auth
    build: ryver-auth
    depends_on:
      - registry
      - gateway
    ports:
      - "8081:8081"
    networks:
      - "ryver-network"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ryver-registry:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  fts:
    image: ryver-fts
    container_name: ryver-fts
    build: ryver-fts
    depends_on:
      - registry
      - gateway
      - auth
    ports:
      - "8083:8083"
    networks:
      - "ryver-network"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ryver-registry:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  cms:
    image: ryver-cms
    container_name: ryver-cms
    build: ryver-cms
    depends_on:
      - registry
      - gateway
      - auth
    ports:
      - "8082:8082"
    networks:
      - "ryver-network"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ryver-registry:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

  market:
    image: ryver-market
    container_name: ryver-market
    build: ryver-market
    depends_on:
      - registry
      - gateway
      - auth
      - fts
    ports:
      - "8086:8086"
    links:
      - fts
    networks:
      - "ryver-network"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://ryver-registry:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true

